version: "3.4"
name: chat-app
services:
  chat-db:
    container_name: chat-db
    image: mariadb:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: ChatDB
    ports:
      - "3306:3306"
    volumes:
      - "./db/db.sql:/docker-entrypoint-initdb.d/1.sql"
  chat-server:
    build: ./server
    container_name: chat-server
    ports:
      - "3000:3000"
    depends_on:
      - chat-db
    volumes:
      - ./server:/app
    environment:
      DB_HOST: chat-db
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: ChatDB
      CHOKIDAR_USEPOLLING: true
  chat-client:
    build: ./client
    container_name: chat-client
    ports:
      - "3001:3001"
    depends_on:
      - chat-server
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
