version: '3.4'
services:
  chat-server:
    build: ./server
    container_name:  chat-server
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
  chat-client:
    build: ./client
    container_name:  chat-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true